config/routes.rb
Rails.application.routes.draw do
  resources :warehouses
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "items#index"
  get 'warehouses/:id', to: 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  validates :warehouse_id, presence: true
  belongs_to :warehouse
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :set_warehouses 
  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:artist, :name, :quantity, :warehouse_id)
    end

    def set_warehouses
      @warehouses = Warehouse.all.order(:name)
    end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: %i[ show edit update destroy ]

  # GET /warehouses or /warehouses.json
  def index
    @warehouses = Warehouse.all
  end

  # GET /warehouses/1 or /warehouses/1.json
  def show
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # GET /warehouses/1/edit
  def edit
  end

  # POST /warehouses or /warehouses.json
  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to warehouse_url(@warehouse), notice: "Warehouse was successfully created." }
        format.json { render :show, status: :created, location: @warehouse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouses/1 or /warehouses/1.json
  def update
    respond_to do |format|
      if @warehouse.update(warehouse_params)
        format.html { redirect_to warehouse_url(@warehouse), notice: "Warehouse was successfully updated." }
        format.json { render :show, status: :ok, location: @warehouse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouses/1 or /warehouses/1.json
  def destroy
    @warehouse.destroy

    respond_to do |format|
      format.html { redirect_to warehouses_url, notice: "Warehouse was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def warehouse_params
      params.require(:warehouse).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :artist, style: "display: block" %>
    <%= form.text_field :artist %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>
  <div>
    <%= form.label :warehouse, style: "display: block" %>
    <%= form.select :warehouse_id, options_for_select(@warehouses.collect { |warehouse| [warehouse.name, warehouse.id]})%>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Artist:</strong>
    <%= item.artist %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= item.quantity %>
  </p>

  <p>
    <strong>Warehouse:</strong>
    <%=item.warehouse.name%>

</div>

app/views/items/edit.html.erb
<div class="container">
  <h1>Editing item</h1>

  <%= render "form", item: @item %>

  <br>

  <div>
    <%= link_to "Show this item", @item %> |
    <%= link_to "Back to items", items_path %> | 
    <%= link_to "Delete this item", @item, method: :delete %><br>
    <%= link_to "Add New Warehouse", new_warehouse_path%><br>

  </div>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
<figure class="text-center">
<h1>Apoya a Las Artistas Cubanas: Items Available</h1>
</figure><br>
<table class="table">
  <thead>
    <tr>
      <th>Artist</th>
      <th>Item Name</th>
      <th>Quantity</th>
      <th>Warehouse</th>
      <th>Action</th>
    </tr>
  </thead>

  
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.artist %></td>
        <td><%= item.quantity%></td>
        <td><%= item.warehouse.name%></td>
        <td><%= link_to "View item details", item %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= turbo_frame_tag "new_warehouse" do %>
    <%= link_to "Add Warehouse", 
               new_warehouse_path,
               data: { turbo_frame: "second_frame"}, 
               class: "btn btn-primary"%> 
<% end %> | 
<%= turbo_frame_tag "new_item" do %>
  <%= link_to "Add item", 
              new_item_path,
              data: { turbo_frame: "third_frame"},
              class: "btn btn-primary" %>
<% end %> 
  <%= turbo_frame_tag "second_frame" do %><% end %>
  <%= turbo_frame_tag "third_frame" do %><% end %>
<br><br>
<%= link_to "View Warehouses", warehouses_path %>
</div>

app/views/items/new.html.erb
  <h1>New item</h1>
<%= turbo_frame_tag "third_frame" do%>
  <%= render "form", item: @item %>
<% end %>

  <br>

  <div>
    <%= link_to "Back to items", items_path %>
  </div>

app/views/items/show.html.erb
<div class="container">
<p style="color: green"><%= notice %></p>
  <%= render @item %>
<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> | <%= link_to "Back to items", items_path %>
  <br>
  <%= button_to "Delete this item", @item, method: :delete %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseCubano</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/warehouses/_form.html.erb
<%= form_with(model: warehouse) do |form| %>
  <% if warehouse.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

      <ul>
        <% warehouse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/warehouses/_warehouse.html.erb
<div id="<%= dom_id warehouse %>">
  <div class="container">
    <div class="row">
      <div class="col">
      <p>
        <strong>Name:</strong>
        <%= warehouse.name %>
      </p>
      </div>

      <% warehouse.items.each do |item| %>
        <p>
          <%= item.name %> | <%= link_to "View Item", item %> 
        </p>
      <% end %>

      <%= link_to "Show this warehouse", warehouse %>

    </div>
  </div>
</div>

app/views/warehouses/edit.html.erb
<h1>Editing warehouse</h1>

<%= render "form", warehouse: @warehouse %>

<br>

<div>
  <%= link_to "Show this warehouse", @warehouse %> |
  <%= link_to "Back to warehouses", warehouses_path %>
</div>

app/views/warehouses/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <%= link_to "Back to Items", root_path %>
  <br>
  <h1>Warehouses</h1>

  <div id="warehouses">
    <% @warehouses.each do |warehouse| %>
      <%= render warehouse %>
      <p>
      </p><br>
    <% end %>
  </div>
<div class="container">
  <%= link_to "Add Warehouse", new_warehouse_path %> | 
</div>
</div>

app/views/warehouses/new.html.erb
<div class="container">
  <h1>New Warehouse</h1>
<%= turbo_frame_tag "second_frame" do %>
  <%= render "form", warehouse: @warehouse %>
<% end %>

  <br>
  <div>
    <%= link_to "Back to warehouses", warehouses_path %>
  </div>
</div>

app/views/warehouses/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <%= render @warehouse %>

  <div>
    <%= link_to "Edit this warehouse", edit_warehouse_path(@warehouse) %> |
    <%= link_to "Back to warehouses", warehouses_path %>

    <%= button_to "Destroy this warehouse", @warehouse, method: :delete %>
    <%= link_to "Back to Items", root_path%>

  </div>
</div>